<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KQ-LP-014" failures="1" tests="5" name="Sanity Tests" time="0.245" errors="0" timestamp="2024-06-07T15:22:44 IST">
  <testcase classname="com.kiwiqa.testNGexamples.GroupIdExmaples" name="method1" time="0.049">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.kiwiqa.testNGexamples.GroupIdExmaples.method1(GroupIdExmaples.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="com.kiwiqa.testNGexamples.GroupIdExmaples" name="method2" time="0.008"/>
  <testcase classname="com.kiwiqa.testNGexamples.GroupIdExmaple" name="method4" time="0.012"/>
  <testcase classname="com.kiwiqa.testNGexamples.GroupIdExmaples" name="method5" time="0.0">
    <skipped/>
  </testcase> <!-- method5 -->
  <testcase classname="com.kiwiqa.testNGexamples.GroupIdExmaple" name="method3" time="0.005"/>
</testsuite> <!-- Sanity Tests -->
